
name: Aggiorna postazioni.json
on:
  workflow_dispatch:
    inputs:
      json_content:
        description: 'Contenuto JSON'
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Aggiorna file
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${{ github.event.inputs.json_content }}" > postazioni.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add postazioni.json
          git commit -m "Aggiornamento postazioni.json"
          git push https://x-access-token:${PAT_TOKEN}@github.com/SamHarker/asset.git HEAD:main
